# Generated by Django 4.2.3 on 2023-07-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='My awesome post', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.secretary')),
            ],
        ),
    ]
